### ISSUE TITLE
 Could not read config file from ru2_combined_400ks_96/config.cfg

### ISSUE THREAD

**Issue by chiboreache** [buriy/spacy-ru#32]
```
wget https://github.com/buriy/spacy-ru/releases/download/v2.3_beta/ru2_combined_400ks_96.zip
unzip ru2_combined_400ks_96.zip

import spacy
nlp = spacy.load('ru2_combined_400ks_96')
```

->

```
Traceback (most recent call last):
  File "/home/chibo/Documents/CODE/BROWSER/onetab_parser/spc-ru.py", line 2, in <module>
    nlp = spacy.load('ru2_combined_400ks_96')
  File "/usr/lib/python3.10/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/usr/lib/python3.10/site-packages/spacy/util.py", line 422, in load_model
    return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
  File "/usr/lib/python3.10/site-packages/spacy/util.py", line 487, in load_model_from_path
    config = load_config(config_path, overrides=overrides)
  File "/usr/lib/python3.10/site-packages/spacy/util.py", line 646, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from ru2_combined_400ks_96/config.cfg
```

**Comment by buriy** [comment]
Doesn't support python 3.10, I suppose. 
Try https://github.com/natasha/natasha-spacy and https://spacy.io/models/ru/

**Comment by chiboreache** [comment]
@buriy похоже на то ага, спасибо за линки, но пока обошелся воркэранудом из коропки `ru_core_news_sm` под мои задачи хватило

----
а ну вот ты как раз его линканул)
